version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-mcp-postgres
    environment:
      POSTGRES_DB: ragmcp
      POSTGRES_USER: ragmcp
      POSTGRES_PASSWORD: ragmcp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ragmcp -d ragmcp"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama:
    image: ollama/ollama:latest
    container_name: rag-mcp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    # Apos subir, execute uma vez:
    #   docker exec -it rag-mcp-ollama ollama pull llama3.1
    #   docker exec -it rag-mcp-ollama ollama pull nomic-embed-text

volumes:
  pgdata:
  ollama-data:

#  curl -F "file=@/home/filipe/Documentos/unipds/estudos2/Documento_teste_Sistemas_rag.pdf" http://localhost:8080/api/documents